name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - v2

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Build browser bundle
        run: npm run build
      - name: Prepare deployment directory
        run: |
          mkdir -p deploy/dist
          cp website/* deploy/
          cp dist/* deploy/dist/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          destination_dir: v${{ steps.package-version.outputs.current-version }}
          user_name: 'moreGeo CI'
          user_email: ci@moregeo.it
          cname: check-stac.moregeo.it

