name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node:
          - '22.1.0' # oldest supported version
          - 'lts/*' # latest LTS version, currently v24
          - 'latest' # latest stable version, currently v25
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.runner }} runner with Node.js ${{ matrix.node }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build browser bundle
        run: npm run build
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run website tests
        run: npm run test:website
