on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [
          'macos-12',
          'macos-13',
          'macos-latest',
          'ubuntu-20.04',
          'ubuntu-22.04',
          'ubuntu-latest',
          'windows-2019',
          'windows-2022',
          'windows-latest',
        ]
        node: [ '18', '20', '22',  '23', 'lts/*' ]
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.runner }} runner with Node.js ${{ matrix.node }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build browser bundle
        run: npm run build

