on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [
          'macos-10.15',
          'macos-11',
          'macos-latest',
          'ubuntu-18.04',
          'ubuntu-20.04',
          'ubuntu-latest',
          'windows-2019',
          'windows-2022',
          'windows-latest',
        ]
        node: [ '14', '16', 'lts/*' ]
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.runner }} runner with Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
