name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node:
          - '20'
          - '22'
          - '23'
          - '24'
          - 'lts/*'
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.runner }} runner with Node.js ${{ matrix.node }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build browser bundle
        run: npm run build

